-- AccuSeat Database Schema
-- Run this in Supabase SQL Editor

-- Enable RLS
alter table if exists venues enable row level security;
alter table if exists sections enable row level security;
alter table if exists rows enable row level security;
alter table if exists seats enable row level security;
alter table if exists photos enable row level security;
alter table if exists share_links enable row level security;
alter table if exists share_link_items enable row level security;

-- Venues table
CREATE TABLE IF NOT EXISTS venues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    location TEXT,
    description TEXT,
    total_seats INTEGER,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sections table (levels/sections within a venue)
CREATE TABLE IF NOT EXISTS sections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    venue_id UUID NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    level TEXT NOT NULL, -- e.g., "100-Level", "200-Level", "Premium"
    section_number TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rows table
CREATE TABLE IF NOT EXISTS rows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id UUID NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    row_number TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seats table
CREATE TABLE IF NOT EXISTS seats (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    row_id UUID NOT NULL REFERENCES rows(id) ON DELETE CASCADE,
    seat_number TEXT NOT NULL,
    price DECIMAL(10,2),
    plan_type TEXT,
    term_length TEXT,
    payment_plan TEXT,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Photos table (360° images)
CREATE TABLE IF NOT EXISTS photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seat_id UUID NOT NULL REFERENCES seats(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    public_url TEXT NOT NULL,
    file_size INTEGER,
    metadata JSONB, -- EXIF data, dimensions, etc.
    uploaded_by UUID REFERENCES auth.users(id),
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- User venue assignments (which reps can access which venues)
CREATE TABLE IF NOT EXISTS user_venues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    venue_id UUID REFERENCES venues(id) ON DELETE CASCADE, -- NULL for admins
    role TEXT NOT NULL DEFAULT 'rep', -- 'admin', 'rep'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, venue_id)
);

-- Share links (generated by reps for prospects)
CREATE TABLE IF NOT EXISTS share_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token TEXT UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'),
    created_by UUID NOT NULL REFERENCES auth.users(id),
    venue_id UUID NOT NULL REFERENCES venues(id),
    client_name TEXT,
    client_phone TEXT,
    client_email TEXT,
    notes TEXT,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    view_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Share link items (seats included in a share)
CREATE TABLE IF NOT EXISTS share_link_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_link_id UUID NOT NULL REFERENCES share_links(id) ON DELETE CASCADE,
    seat_id UUID NOT NULL REFERENCES seats(id),
    option_order INTEGER NOT NULL DEFAULT 1, -- Option 1, 2, 3, etc.
    rep_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CRM logs (Salesforce/Dynamics integration)
CREATE TABLE IF NOT EXISTS crm_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_link_id UUID NOT NULL REFERENCES share_links(id),
    crm_type TEXT NOT NULL, -- 'salesforce', 'dynamics'
    activity_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'success', 'failed'
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Analytics events
CREATE TABLE IF NOT EXISTS analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_link_id UUID REFERENCES share_links(id),
    event_type TEXT NOT NULL, -- 'view', 'like', 'dislike', 'share'
    seat_id UUID REFERENCES seats(id),
    user_agent TEXT,
    ip_address TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Feedback from prospects
CREATE TABLE IF NOT EXISTS prospect_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_link_id UUID NOT NULL REFERENCES share_links(id) ON DELETE CASCADE,
    seat_id UUID REFERENCES seats(id),
    feedback_type TEXT NOT NULL, -- 'like', 'dislike'
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rep notifications
CREATE TABLE IF NOT EXISTS rep_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'feedback', 'view', 'share'
    title TEXT NOT NULL,
    message TEXT,
    share_link_id UUID REFERENCES share_links(id),
    seat_id UUID REFERENCES seats(id),
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for notifications
CREATE INDEX IF NOT EXISTS idx_rep_notifications_user ON rep_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_rep_notifications_read ON rep_notifications(read);
CREATE INDEX IF NOT EXISTS idx_prospect_feedback_link ON prospect_feedback(share_link_id);

-- RLS for notifications
ALTER TABLE rep_notifications ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert notifications (for anonymous prospect feedback)
CREATE POLICY "Anyone can insert notifications" ON rep_notifications
    FOR INSERT WITH CHECK (true);

-- Users can only view their own notifications
CREATE POLICY "Users can view own notifications" ON rep_notifications
    FOR SELECT USING (user_id = auth.uid());

-- Users can only update their own notifications
CREATE POLICY "Users can update own notifications" ON rep_notifications
    FOR UPDATE USING (user_id = auth.uid());

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sections_venue ON sections(venue_id);
CREATE INDEX IF NOT EXISTS idx_rows_section ON rows(section_id);
CREATE INDEX IF NOT EXISTS idx_seats_row ON seats(row_id);
CREATE INDEX IF NOT EXISTS idx_photos_seat ON photos(seat_id);
CREATE INDEX IF NOT EXISTS idx_user_venues_user ON user_venues(user_id);
CREATE INDEX IF NOT EXISTS idx_user_venues_venue ON user_venues(venue_id);
CREATE INDEX IF NOT EXISTS idx_share_links_token ON share_links(token);
CREATE INDEX IF NOT EXISTS idx_share_link_items_link ON share_link_items(share_link_id);
CREATE INDEX IF NOT EXISTS idx_analytics_share_link ON analytics_events(share_link_id);

-- RLS Policies

-- Venues: Admins can see all, reps only see assigned
CREATE POLICY "Venues viewable by assigned users" ON venues
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM user_venues 
            WHERE user_venues.venue_id = venues.id 
            AND user_venues.user_id = auth.uid()
        )
        OR
        EXISTS (
            SELECT 1 FROM user_venues 
            WHERE user_venues.user_id = auth.uid() 
            AND user_venues.role = 'admin'
        )
    );

-- Sections: Viewable if user has access to parent venue
CREATE POLICY "Sections viewable by venue users" ON sections
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM user_venues 
            WHERE user_venues.venue_id = sections.venue_id 
            AND user_venues.user_id = auth.uid()
        )
    );

-- Rows: Viewable through section
CREATE POLICY "Rows viewable by section users" ON rows
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM sections 
            JOIN user_venues ON user_venues.venue_id = sections.venue_id
            WHERE rows.section_id = sections.id 
            AND user_venues.user_id = auth.uid()
        )
    );

-- Seats: Viewable through row
CREATE POLICY "Seats viewable by row users" ON seats
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM rows 
            JOIN sections ON sections.id = rows.section_id
            JOIN user_venues ON user_venues.venue_id = sections.venue_id
            WHERE seats.row_id = rows.id 
            AND user_venues.user_id = auth.uid()
        )
    );

-- Photos: Viewable through seat
CREATE POLICY "Photos viewable by seat users" ON photos
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM seats 
            JOIN rows ON rows.id = seats.row_id
            JOIN sections ON sections.id = rows.section_id
            JOIN user_venues ON user_venues.venue_id = sections.venue_id
            WHERE photos.seat_id = seats.id 
            AND user_venues.user_id = auth.uid()
        )
    );

-- Share links: Creators can view their own
CREATE POLICY "Share links viewable by creator" ON share_links
    FOR SELECT USING (created_by = auth.uid());

-- Share links: Anyone can view by token (for public links)
CREATE POLICY "Share links viewable by token" ON share_links
    FOR SELECT USING (true); -- Token-based access control in app logic

-- Share link items: Viewable through share link
CREATE POLICY "Share link items viewable through link" ON share_link_items
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM share_links 
            WHERE share_links.id = share_link_items.share_link_id
        )
    );

-- User venues: Users can see their own assignments
CREATE POLICY "User venues viewable by self" ON user_venues
    FOR SELECT USING (user_id = auth.uid());

-- Analytics: Insert allowed for tracking (no auth required for public links)
CREATE POLICY "Analytics insertable by anyone" ON analytics_events
    FOR INSERT WITH CHECK (true);

-- Enable realtime for share links (for live feedback)
alter publication supabase_realtime add table share_links;
alter publication supabase_realtime add table analytics_events;

-- Function to increment view count
CREATE OR REPLACE FUNCTION increment_view_count(link_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE share_links
  SET view_count = view_count + 1
  WHERE id = link_id;
END;
$$ LANGUAGE plpgsql;
